"""Materialize verified memory into the flat files harnesses already read.

This is the portability half of the design: an agent that has never heard of
nenapu still picks the memory up, because it lands in CLAUDE.md / AGENTS.md
inside a managed block. Everything outside the markers is left untouched.
"""

from __future__ import annotations

from pathlib import Path

from .models import Kind, Status, VerifyStatus
from .store import Store, effective_confidence

BEGIN = "<!-- BEGIN NENAPU -->"
END = "<!-- END NENAPU -->"

_SECTION_ORDER = [Kind.USER, Kind.FEEDBACK, Kind.PROJECT, Kind.ENVIRONMENT, Kind.REFERENCE]
_SECTION_TITLE = {
    Kind.USER: "About the user",
    Kind.FEEDBACK: "Working agreements",
    Kind.PROJECT: "Project context",
    Kind.ENVIRONMENT: "Environment",
    Kind.REFERENCE: "References",
}


def render(
    store: Store,
    *,
    scope: str | None = None,
    limit: int = 60,
    min_confidence: float = 0.35,
) -> str:
    """Render the managed block. Low-confidence facts are simply omitted —
    a stale memory is worse than a missing one."""
    facts = [
        (f, effective_confidence(f))
        for f in store.list_facts(scope=scope, status=Status.ACTIVE, limit=5000)
    ]
    facts = [(f, c) for f, c in facts if c >= min_confidence]
    facts.sort(key=lambda t: t[1], reverse=True)
    facts = facts[:limit]

    lines = [BEGIN, "<!-- Generated by nenapu. Edits inside this block are overwritten. -->", ""]
    if not facts:
        lines += ["_No memory above the confidence threshold._", "", END]
        return "\n".join(lines)

    by_kind: dict[str, list] = {}
    for f, c in facts:
        by_kind.setdefault(f.kind, []).append((f, c))

    for kind in _SECTION_ORDER:
        group = by_kind.get(kind)
        if not group:
            continue
        lines.append(f"### {_SECTION_TITLE[kind]}")
        for f, c in group:
            marks = []
            if f.verify_status == VerifyStatus.PASS:
                marks.append("verified")
            elif f.verify_status == VerifyStatus.FAIL:
                marks.append("CHECK FAILING")
            marks.append(f"{c:.0%}")
            lines.append(f"- {f.text} _({', '.join(marks)})_")
        lines.append("")

    lines.append(END)
    return "\n".join(lines)


def write_file(
    path: str | Path,
    store: Store,
    *,
    scope: str | None = None,
    limit: int = 60,
    min_confidence: float = 0.35,
) -> Path:
    """Splice the managed block into a file, creating it if absent."""
    target = Path(path).expanduser()
    block = render(store, scope=scope, limit=limit, min_confidence=min_confidence)

    if target.exists():
        original = target.read_text()
        if BEGIN in original and END in original:
            head = original.split(BEGIN)[0]
            tail = original.split(END, 1)[1]
            target.write_text(f"{head}{block}{tail}")
            return target
        sep = "" if original.endswith("\n\n") else ("\n" if original.endswith("\n") else "\n\n")
        target.write_text(f"{original}{sep}{block}\n")
        return target

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(f"{block}\n")
    return target
